trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'

- script: |
    echo "Deploying to GitHub Pages..."
    # Push HTML/CSS files to gh-pages branch
    git config user.name "GitHub Actions"
    git config user.email "<email>"
    git add .
    git commit -m "Deploy to GitHub Pages"
    git push origin gh-pages
  displayName: 'Deploy to GitHub Pages'